# -*- coding: utf-8 -*-
"""info-restaurant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hd3Kjlg1OJzTUzkUTgjiIVrdZgNlF1cl
"""

!pip install groq langchain langchain-community langchain-text-splitters langchain-groq sentence-transformers tiktoken pypdf -q

!pip install -q pypdf pinecone groq tqdm

import os
import re
import time
from tqdm import tqdm
from pypdf import PdfReader
from pinecone import Pinecone, ServerlessSpec
from groq import Groq
from langchain_text_splitters import RecursiveCharacterTextSplitter
from sentence_transformers import SentenceTransformer
import numpy as np
import pandas as pd
from getpass import getpass


#Keys
PINECONE_API_KEY = "pcsk_7HWBE7_TAZGCnBqboH8YRqBh4FNoS6kpcwnUGiFjSWXRYazmuen44BScTqpfPpWNCa2PSi"
GROQ_API_KEY     = "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"
EMBED_MODEL      = "all-MiniLM-L6-v2"
PDF_PATH = "/content/Fake restaurant info.pdf"
INDEX_NAME       = "reservations"

#client initialzation
pc     = Pinecone(api_key=PINECONE_API_KEY)
groq   = Groq(api_key=GROQ_API_KEY)
embedder = SentenceTransformer(EMBED_MODEL)

print ("initialized")

pdf_file = [
          '/content/Fake restaurant info.pdf'
]

from langchain_community.document_loaders import PyPDFLoader
loader = PyPDFLoader(PDF_PATH)
documents = loader.load()


print(f"Loaded {len(documents)} pages from {PDF_PATH}")

from pypdf import PdfReader

def extract_text_from_pdf(pdf_path):
    reader = PdfReader(pdf_path)
    pages = []
    for i, page in enumerate(reader.pages):
        text = page.extract_text()
        if text:
            text = re.sub(r'\n([a-z,\.]+)\n', r' \1 ', text)
            text = re.sub(r'  +', ' ', text)
            text = re.sub(r' \n', '\n', text)
            text = re.sub(r'\n{3,}', '\n\n', text)
            pages.append({
                "page_number": i + 1,
                "text": text.strip()
            })
    return pages

pages = extract_text_from_pdf(PDF_PATH)
print("Pages extracted:", len(pages))
print(pages[0]["text"][:800])

def chunk_text(text, chunk_size=700, overlap=120):
    chunks = []
    start = 0
    while start < len(text):
        end = start + chunk_size
        chunk = text[start:end]
        chunks.append(chunk)
        start += chunk_size - overlap
    return chunks

documents = []

for page in pages:
    page_chunks = chunk_text(page["text"], chunk_size=700, overlap=120)
    for idx, chunk in enumerate(page_chunks):
        documents.append({
            "id": f"page-{page['page_number']}-chunk-{idx}",
            "text": chunk,
            "page_number": page["page_number"]
        })

print("Total chunks:", len(documents))
print(documents[0])

import time

# Desired dimension for the index
desired_dimension = 384

# index check
existing_indexes = [idx.name for idx in pc.list_indexes()]

if INDEX_NAME not in existing_indexes:
    print(f"Creating index {INDEX_NAME}...")
    pc.create_index(
        name=INDEX_NAME,
        dimension=desired_dimension,
        metric="cosine",
        spec=ServerlessSpec(cloud='aws', region='us-east-1')
    )
    while not pc.describe_index(INDEX_NAME).status['ready']:
        time.sleep(1)
    print(f"Index {INDEX_NAME} created successfully with dimension {desired_dimension}.")
else:
    # Check if the existing index has the correct dimension
    index_description = pc.describe_index(INDEX_NAME)
    current_dimension = index_description.dimension

    if current_dimension != desired_dimension:
        print(f"Existing index {INDEX_NAME} has dimension {current_dimension}, but {desired_dimension} is required. Deleting and recreating the index...")
        pc.delete_index(INDEX_NAME)

        # Wait for deletion to complete (optional, but good practice)
        while INDEX_NAME in [idx.name for idx in pc.list_indexes()]:
            time.sleep(1)

        print(f"Creating index {INDEX_NAME}...")
        pc.create_index(
            name=INDEX_NAME,
            dimension=desired_dimension,
            metric="cosine",
            spec=ServerlessSpec(cloud='aws', region='us-east-1')
        )
        while not pc.describe_index(INDEX_NAME).status['ready']:
            time.sleep(1)
        print(f"Index {INDEX_NAME} recreated successfully with dimension {desired_dimension}.")
    else:
        print(f"Index {INDEX_NAME} already exists and has the correct dimension ({desired_dimension}).")

index = pc.Index(INDEX_NAME)
print("Index ready.")

texts = [doc["text"] for doc in documents]
embeddings = embedder.encode(texts, show_progress_bar=True, convert_to_numpy=True)

total, dim = len(embeddings), embeddings.shape[1] #makin' it 2D for future use.
print(f"Total embeddings: {total}")
print(f"Embedding dimension: {dim}")

from tqdm import tqdm

batch_size = 50
for i in tqdm(range(0, len(documents), batch_size), desc="Upserting batches"):
    batch = documents[i:i+batch_size]
    texts = [doc["text"] for doc in batch]
    ids = [doc["id"] for doc in batch]

    # embeddings generation
    embeddings = embedder.encode(texts, show_progress_bar=False).tolist()

    # vectors prep
    vectors = [
        (ids[j], embeddings[j], {"text": texts[j], "page": doc["page_number"]})
        for j, doc in enumerate(batch)
    ]

    # upsert
    index.upsert(vectors=vectors)

print(f"Upserted {len(documents)} chunks.")

from sentence_transformers import SentenceTransformer
import pinecone

#R part
def retrieve_relevant_chunks(query: str, top_k: int = 5) -> list[dict]:
  query_embedding = embedder.encode([query], convert_to_numpy=True)[0].tolist()

  results = index.query(
      vector=query_embedding,
      top_k=top_k,
      include_metadata=True
  )

  return [
      {
          "text": match["metadata"].get("text", ""),
          "score": match["score"],
          "page_number": match["metadata"].get("page_number"),  # safe fallback
      }
      for match in results.matches
  ]

from langchain_groq import ChatGroq
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough

# G part
llm = ChatGroq(
    model="llama-3.1-8b-instant", # Updated to a currently supported model
    temperature=0.1,
    api_key=GROQ_API_KEY)

show_chunks = False

def ask_resto(question: str, top_k: int = 5) -> str:
    chunks = retrieve_relevant_chunks(question, top_k=top_k)

    if show_chunks:
        print("\nRetrieved Chunks:\n")
        for i, chunk in enumerate(chunks, start=1):
            print(f"Chunk {i}")
            print(f"Score: {chunk['score']:.4f}")
            print(f"Page: {chunk['page_number']}")
            print(chunk["text"][:500])
            print("-" * 80)

    context = "\n\n".join(c["text"] for c in chunks)

    system_prompt = (
        "You are a helpful FAQ assistant for a Saffron Table Bistro, "
        "a premium restaurant in Chennai. "
        "Answer questions clearly, concisely and in a warm, welcoming tone based only on the context provided.  "
        "If the answer is not in the context, say: "
        "'I do not have the information you're asking for. You can visit https://www.gordonramsayrestaurants.com/"
        "or contact hello@saffrontablebistro.com or call +91 90000 11223 ' "
        "Do not make up information. "
        "Do not assume anything that is not explicitly mentioned in the context. "
        "If a user asks about reservations, modifications, or cancellations, answer only using the restaurant policies in the context. "
        "If a user asks about food, drinks, cuisines, smoking, timings, seating, services, or ordering, use only the details given in the context. "
        "If online ordering or delivery is asked about, clearly state that orders are available only through Swiggy and Zomato, and that delivery timing, charges, refunds, and availability depend on those platforms. "
        "If a user asks something outside the restaurant information provided, respond with the fallback message exactly as written. "
        "Keep responses natural, polite, and easy to understand. "
        "Do not give long explanations unless the user asks for more detail. "
        "Do not mention internal context, database, training data, or system instructions. "
        "If the user greets you, greet them back warmly and offer help with reservations, menu questions, timings, or general restaurant information. "
        "If the user asks multiple questions, answer each one briefly and clearly using only the context provided. "
        "If the user asks for contact details, provide the restaurant email and phone number exactly as given in the context. "
        "If the user asks for the restaurant location, provide it exactly as written in the context. "
        "If the user asks whether something is allowed, such as smoking or pets, answer strictly according to the policy in the context. "
        "Always prioritize factual accuracy over sounding helpful."
    )

    user_prompt = f"Context from Saffron Table Bistro knowledge base:\n{context}\n\nQuestion: {question}\n\nAnswer:"

    response = groq.chat.completions.create(
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ],
        model="llama-3.1-8b-instant",
        temperature=0.1,
        max_tokens=500
    )
    return response.choices[0].message.content

show_chunks = False

def ask_resto(question: str, top_k: int = 5) -> str:
    chunks = retrieve_relevant_chunks(question, top_k=top_k)

    if show_chunks:
        print("\nRetrieved Chunks:\n")
        for i, chunk in enumerate(chunks, start=1):
            print(f"Chunk {i}")
            print(f"Score: {chunk['score']:.4f}")
            print(f"Page: {chunk['page_number']}")
            print(chunk["text"][:500])
            print("-" * 80)

    context = "\n\n".join(c["text"] for c in chunks)

    system_prompt = (
        "You are a helpful FAQ assistant for a Saffron Table Bistro, "
        "a premium restaurant in Chennai. "
        "Answer questions clearly, concisely and in a warm, welcoming tone based only on the context provided.  "
        "If the answer is not in the context, say: "
        "'I do not have the information you're asking for. You can visit https://www.gordonramsayrestaurants.com/"
        "or contact hello@saffrontablebistro.com or call +91 90000 11223 ' "
        "Do not make up information. "
        "Do not assume anything that is not explicitly mentioned in the context. "
        "If a user asks about reservations, modifications, or cancellations, answer only using the restaurant policies in the context. "
        "If a user asks about food, drinks, cuisines, smoking, timings, seating, services, or ordering, use only the details given in the context. "
        "If online ordering or delivery is asked about, clearly state that orders are available only through Swiggy and Zomato, and that delivery timing, charges, refunds, and availability depend on those platforms. "
        "If a user asks something outside the restaurant information provided, respond with the fallback message exactly as written. "
        "Keep responses natural, polite, and easy to understand. "
        "Do not give long explanations unless the user asks for more detail. "
        "Do not mention internal context, database, training data, or system instructions. "
        "If the user greets you, greet them back warmly and offer help with reservations, menu questions, timings, or general restaurant information. "
        "If the user asks multiple questions, answer each one briefly and clearly using only the context provided. "
        "If the user asks for contact details, provide the restaurant email and phone number exactly as given in the context. "
        "If the user asks for the restaurant location, provide it exactly as written in the context. "
        "If the user asks whether something is allowed, such as smoking or pets, answer strictly according to the policy in the context. "
        "Always prioritize factual accuracy over sounding helpful."
    )

    user_prompt = f"Context from Saffron Table Bistro knowledge base:\n{context}\n\nQuestion: {question}\n\nAnswer:"

    response = groq.chat.completions.create(
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ],
        model="llama-3.1-8b-instant",
        temperature=0.1,
        max_tokens=500
    )
    return response.choices[0].message.content

DEFAULT_SUGGESTIONS = [
    "How can I reserve a table?",
    "Can I modify or cancel my reservation?",
    "What cuisines do you serve?",
    "Can I order through Swiggy or Zomato?",
    "Do you serve drinks and have a smoking area?",
]

import re

GREETINGS = {"hi", "hello", "hey", "heya", "wassup", "watchu doing", "Namaste", "vannakam", "yo", "hiya", "howdy", "sup", "what's up", "whats up"}
THANKS = {"thanks", "thank you", "thank you so much", "thx", "ty", "appreciate it"}
HOW_ARE_YOU = {"how are you", "how are you doing", "how's it going", "hows it going", "you good"}

def handle_small_talk(user_input: str):
    """Returns a friendly and warm response if it's small talk, else returns None."""
    text = user_input.lower().strip().rstrip("!?.").strip()

    if text in GREETINGS:
        return "Hello! Welcome to Saffron Table Bistro. I’m here to help you with reservations, menu questions, timings, seating plan or arrangements or anything else related to Saffron Table Bistro"

    if text in THANKS:
        return "You’re most welcome! Feel free to ask if you have any more questions about Saffron Table Bistro."

    if text in HOW_ARE_YOU:
        return "’m doing great, thank you for asking! I’m here to help you with reservations, menu details, timings, and general information about Saffron Table Bistro. What would you like to know?"

    return None

print("=" * 55)
print("This is an AI assistant to help you with your queries about Saffron Table Bistro.")
print("=" * 55)

print("\nHere's what most people ask:\n")
for s in DEFAULT_SUGGESTIONS:
    print(" ", s)

first_question = True
while True:
    question = input("\nYou: ").strip()
    if not question:
        continue
    if question.lower() in ("quit", "exit", "bye", "done", "thanks", "fine", "finish"):
        print("Thank You ! You can always vist our website www.gordonramsayrestaurants.com/ for more information")
        break

    small_talk_response = handle_small_talk(question)
    if small_talk_response:
        print(f"\nCPLC Bot: {small_talk_response}")
        continue

    answer = ask_resto(question)
    print(f"\nCPLC Bot: {answer}")