# -*- coding: utf-8 -*-
"""menu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/118bylwKn-gmWc9si1v6ckzWhTaDDSfKI
"""

!pip install -q pinecone openai pypdf tiktoken

!pip install -q groq

import os
import pandas as pd
import numpy as np
import uuid
from groq import Groq
from getpass import getpass

from pinecone import Pinecone, ServerlessSpec
from sentence_transformers import SentenceTransformer

#Keys
PINECONE_API_KEY = "pcsk_7HWBE7_TAZGCnBqboH8YRqBh4FNoS6kpcwnUGiFjSWXRYazmuen44BScTqpfPpWNCa2PSi"
GROQ_API_KEY     = "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"
EMBED_MODEL      = "all-MiniLM-L6-v2"
INDEX_NAME       = "reservations"


groq_client = Groq(api_key=GROQ_API_KEY)
pc = Pinecone(api_key=PINECONE_API_KEY)

# Pass the HF_TOKEN to SentenceTransformer if it was provided
hf_token = os.environ.get("HF_TOKEN") # Safely get HF_TOKEN
if hf_token:
    embedding_model = SentenceTransformer(EMBED_MODEL, token=hf_token)
else:
    embedding_model = SentenceTransformer(EMBED_MODEL)
print("Embedding model loaded!")

csv_files = [
    'saffron_table_menu_dataset_ffs_bb.csv'
]

dataframes = {}
for file_path in csv_files:
    try:
        df_name = file_path.replace('.csv', '')
        dataframes[df_name] = pd.read_csv(file_path, encoding='latin-1')
        print(f"Successfully loaded {file_path} into dataframe '{df_name}'.")
        print(f"First 5 rows of {df_name}:")
        print(dataframes[df_name].head())
        print("\n")
    except FileNotFoundError:
        print(f"Error: File not found at {file_path}")
    except Exception as e:
        print(f"Error loading {file_path}: {e}")

menua1 = pd.read_csv("/content/saffron_table_menu_dataset_ffs_bb.csv", encoding='latin-1')

print("menua1", menua1.shape)

dataframes = [("menua1", menua1)]

for name, df in dataframes:
    print(f"{name} columns: {df.columns.tolist()}")

for df in [menua1]:
    df.columns = df.columns.str.strip()

for col in menua1.select_dtypes(include="object").columns:
    menua1[col] = menua1[col].astype(str).str.strip()

def normalise_menu(raw_df):
    #cleaning
    df = raw_df.copy()
    for col in df.select_dtypes(include="object").columns:
        df[col] = df[col].fillna("").astype(str).str.strip()
    for col in ["Record_Type", "Cuisine", "Category", "Dietary_Tags", "Beverage_Type"]:
        if col in df.columns:
            df[col] = df[col].str.title()
    return df

def build_summary_docs(df):
    docs = []

    cuisines      = sorted([c for c in df["Cuisine"].unique() if c and c != "Alcohol"])
    food_cats     = sorted([c for c in df["Category"].unique() if c and c != "Alcoholic Beverage"])
    alcohol_types = sorted([b for b in df["Beverage_Type"].unique() if b])
    dietary_tags  = sorted([t for t in df["Dietary_Tags"].unique() if t])

    master_text = (
        f"Saffron Table Bistro menu overview. "
        f"Available cuisines: {', '.join(cuisines)}. "
        f"Food categories available: {', '.join(food_cats)}. "
        f"Alcohol menu available: Yes. "
        f"Alcohol types available: {', '.join(alcohol_types)}. "
        f"Dietary tags found in dataset: {', '.join(dietary_tags)}."
    )
    docs.append({
        "id": "summary-master",
        "text": master_text,
        "metadata": {"doc_type": "summary", "section": "master_overview"}
    })

    for cuisine in cuisines:
        sub = df[(df["Cuisine"] == cuisine) & (df["Record_Type"] == "Food")]
        cats  = sorted(sub["Category"].unique())
        tags  = sorted(sub["Dietary_Tags"].unique())
        items = sorted(sub["Item_Name"].unique())
        text = (
            f"Cuisine summary for {cuisine}. "
            f"Categories: {', '.join(cats)}. "
            f"Dietary options: {', '.join(tags)}. "
            f"Example dishes: {', '.join(items[:10])}. "
            f"Total items: {len(sub)}."
        )
        docs.append({
            "id": f"summary-cuisine-{cuisine.lower().replace(' ', '-')}",
            "text": text,
            "metadata": {"doc_type": "summary", "section": "cuisine_summary", "cuisine": cuisine}
        })

        alc = df[df["Record_Type"] == "Alcohol"]
    if len(alc) > 0:
        bev_types = sorted(alc["Beverage_Type"].unique())
        text = (
            f"Alcohol menu summary. "
            f"Available types: {', '.join(bev_types)}. "
            f"Total alcohol items: {len(alc)}. "
            f"Served only to guests above 21 years of age; valid ID may be requested."
        )
        docs.append({
            "id": "summary-alcohol",
            "text": text,
            "metadata": {"doc_type": "summary", "section": "alcohol_summary"}
        })

    return docs

def build_item_docs(df):
    df = normalise_menu(df)
    docs = []

    for _, row in df.iterrows():
        is_alcohol = row["Record_Type"].strip().lower() == "alcohol"

        if is_alcohol:
            text = (
                f"Alcohol menu item. "
                f"Name: {row['Item_Name']}. "
                f"Alcohol type: {row['Beverage_Type']}. "
                f"Cuisine: {row['Cuisine']}. "
                f"Description: {row['Description']}. "
                f"Rating: {row['Rating']}. "
                f"Best pairing: {row['Best_Pairing']}. "
                f"Served only to guests above 21 years old; valid ID may be requested."
            )
        else:
            text = (
                f"Food menu item. "
                f"Name: {row['Item_Name']}. "
                f"Cuisine: {row['Cuisine']}. "
                f"Category: {row['Category']}. "
                f"Dietary tag: {row['Dietary_Tags']}. "
                f"Description: {row['Description']}. "
                f"Rating: {row['Rating']}. "
                f"Best pairing: {row['Best_Pairing']}. "
                f"Spice level: {row['Spice_Level']}."
            )

        try:
            rating_val = float(row["Rating"]) if str(row["Rating"]).strip() else None
        except (ValueError, TypeError):
            rating_val = None

        docs.append({
            "id": str(row["Menu_ID"]),
            "text": text,
            "metadata": {
                "doc_type":      "item",
                "menu_id":       str(row["Menu_ID"]),
                "record_type":   str(row["Record_Type"]),
                "cuisine":       str(row["Cuisine"]),
                "category":      str(row["Category"]),
                "item_name":     str(row["Item_Name"]),
                "dietary_tag":   str(row["Dietary_Tags"]),
                "beverage_type": str(row["Beverage_Type"]),
                "rating":        rating_val,
            }
        })

    return docs

def build_all_docs(menu_df):
    df = normalise_menu(menu_df)
    summary_docs = build_summary_docs(df)
    item_docs    = build_item_docs(df)
    all_docs     = summary_docs + item_docs
    print(f"Summary docs : {len(summary_docs)}")
    print(f"Item docs    : {len(item_docs)}")
    print(f"Total docs   : {len(all_docs)}")

    return all_docs, df

def get_menu_summary(df):
    food_df = df[df["Record_Type"] == "Food"]
    alc_df  = df[df["Record_Type"] == "Alcohol"]

    lines = ["Welcome to Saffron Table Bistro! Have a look at what we offer:\n"]

    lines.append("FOOD CUISINES:")
    for cuisine, grp in food_df.groupby("Cuisine"):
        cats = grp["Category"].dropna().unique().tolist()
        lines.append(f" {cuisine}  ({', '.join(cats)})")

    lines.append("\nBEVERAGES & ALCOHOL:")
    for btype, grp in alc_df.groupby("Beverage_Type", dropna=True):
        lines.append(f" {btype} ({len(grp)} options)")

    lines.append("\n DIETARY OPTIONS:  Vegetarian | Vegan | Chicken | Seafood | Lamb | Beef")
    lines.append("\nWhat would you like to explore today?")
    return "\n".join(lines)

def _get_reference_values(df):
    food_cuisines   = sorted(df[df["Record_Type"] == "Food"]["Cuisine"].dropna().unique().tolist())
    beverage_types  = sorted(df[df["Record_Type"] == "Alcohol"]["Beverage_Type"].dropna().unique().tolist())
    food_categories = sorted(df[df["Record_Type"] == "Food"]["Category"].dropna().unique().tolist())
    return food_cuisines, beverage_types, food_categories


def _fuzzy_match(user_text, options):
    user_lower = user_text.lower()
    for opt in options:
        if opt.lower() in user_lower:
            return opt
    return None


def fresh_state():
    return {
        "step":         0,

        "record_type":  None,
        "cuisine":      None,
        "category":     None,
        "beverage_type": None,
        "diet":         None,
    }


def parse_user_input(user_input, state, df):
    food_cuisines, beverage_types, food_categories = _get_reference_values(df)

    user_lower = user_input.lower().strip()
    prompt     = ""
    ready      = False

    if user_lower in {"reset", "start over", "restart", "back"}:
        state  = fresh_state()
        prompt = "Session reset. " + get_menu_summary(df)
        return state, False, prompt

    if state["step"] == 0:
        alcohol_keywords = {"alcohol", "drink", "beverage", "cocktail", "beer",
                            "wine", "spirits", "whisky", "whiskey", "rum", "vodka",
                            "bourbon", "martini"}
        if any(kw in user_lower for kw in alcohol_keywords):
            state["record_type"] = "Alcohol"
            state["step"]        = 1
            prompt = f"Great choice! Which type of beverage? Options: {', '.join(beverage_types)}"
        else:
            matched = _fuzzy_match(user_input, food_cuisines)
            if matched:
                state["record_type"] = "Food"
                state["cuisine"]     = matched
                state["step"]        = 2
                prompt = f"Excellent! You chose {matched} cuisine.\nWhich category? Options: {', '.join(food_categories)}"
            else:
                prompt = (
                    f"Sorry, I didn't catch that. Please choose a cuisine: "
                    f"{', '.join(food_cuisines)}\n"
                    f"or say 'alcohol' / 'drinks' for beverages."
                )

    elif state["step"] == 1 and state["record_type"] == "Alcohol":
        if user_lower in {"all", "any", "skip"}:
            state["beverage_type"] = None
        else:
            matched = _fuzzy_match(user_input, beverage_types)
            if matched:
                state["beverage_type"] = matched
            else:
                prompt = f"Please pick a beverage type: {', '.join(beverage_types)}"
                return state, False, prompt
        state["step"] = 4
        ready  = True
        prompt = "Fetching your drinks menu…"

    elif state["step"] == 2 and state["record_type"] == "Food":
        if user_lower in {"all", "any", "skip"}:
            state["category"] = None
            state["step"]     = 3
            prompt = "Got it, showing all categories. Any dietary preference? (vegetarian / non-veg / all)"
        else:
            matched = _fuzzy_match(user_input, food_categories)
            alias_map = {
                "starter": "Appetizer", "starters": "Appetizer",
                "entree":  "Main",      "entrees":  "Main",
                "mains":   "Main",
            }
            if not matched:
                matched = alias_map.get(user_lower)
            if matched:
                state["category"] = matched
                state["step"]     = 3
                prompt = f"Perfect, {matched}s it is! Any dietary preference? (vegetarian / non-veg / all)"
            else:
                prompt = f"Please choose a category: {', '.join(food_categories)} (or 'all' to skip)"

    elif state["step"] == 3:
        diet_map = {
            "veg":         "Vegetarian",
            "vegetarian":  "Vegetarian",
            "non-veg":     "Non-Vegetarian",
            "nonveg":      "Non-Vegetarian",
            "non veg":     "Non-Vegetarian",
            "vegan":       "Vegan",
            "chicken":     "Chicken",
            "seafood":     "Seafood",
            "all":         "All",
            "any":         "All",
            "skip":        "All",
        }
        matched = diet_map.get(user_lower)
        if matched:
            state["diet"] = matched
            state["step"] = 4
            ready  = True
            prompt = "Searching for the best matches…"
        else:
            prompt = "Please reply with: vegetarian, non-veg, or all."

    else:
        prompt = "Results are ready above! Type 'fresh' to start a new search."

    return state, ready, prompt

def build_filter(state):
    f = {}

    if state["record_type"] == "Food":
        f["record_type"] = "Food"
        if state.get("cuisine"):
            f["cuisine"]  = state["cuisine"]
        if state.get("category"):
            f["category"] = state["category"]
        diet = state.get("diet")
        if diet and diet != "All":
            if diet == "Vegetarian":
                f["dietary_tag"] = "Vegetarian"
            elif diet == "Non-Vegetarian":
                f["dietary_tag"] = {"$ne": "Vegetarian"}

    elif state["record_type"] == "Alcohol":
        f["record_type"] = "Alcohol"
        if state.get("beverage_type"):
            f["beverage_type"] = state["beverage_type"]

    return f


def query_items(state, index, embed_fn, top_k=50):
    if state["record_type"] == "Alcohol":
        query_text = f"alcohol {state.get('beverage_type', 'drink')} menu"
    else:
        parts = ["food menu", state.get("cuisine", ""), state.get("category", ""),
                 state.get("diet", "")]
        query_text = " ".join(p for p in parts if p and p != "All")

    query_vector = embed_fn(query_text)
    pinecone_filter = build_filter(state)

    response = index.query(
        vector    = query_vector,
        top_k     = top_k,
        filter    = pinecone_filter,
        include_metadata = True
    )

    matches = sorted(
        response.get("matches", []),
        key=lambda x: float(x["metadata"].get("rating") or 0),
        reverse=True
    )
    return matches

import time

INDEX_DIM = 384

all_docs, _ = build_all_docs(menua1)

existing = [idx.name for idx in pc.list_indexes()]
if INDEX_NAME not in existing:
    pc.create_index(
        name=INDEX_NAME,
        dimension=INDEX_DIM,
        metric="cosine",
        spec=ServerlessSpec(cloud="aws", region="us-east-1")
    )
    print(f"Index '{INDEX_NAME}' created.")
    time.sleep(5)
else:
    print(f"Index '{INDEX_NAME}' already exists.")

index = pc.Index(INDEX_NAME)

BATCH_SIZE = 50
batch = []

for doc in all_docs:
    embedding = embedding_model.encode(doc["text"]).tolist()
    batch.append({
        "id":       doc["id"],
        "values":   embedding,
        "metadata": doc["metadata"]
    })
    if len(batch) == BATCH_SIZE:
        index.upsert(vectors=batch)
        batch = []

if batch:
    index.upsert(vectors=batch)

print(f"\n Upserted {len(all_docs)} docs into '{INDEX_NAME}'.")
print(index.describe_index_stats())

# R

def retrieve(query, state, top_k=8):
    query_vec = embedding_model.encode(query).tolist()
    pinecone_filter = build_filter(state)

    if pinecone_filter:
        results = index.query(
            vector=query_vec,
            top_k=top_k,
            include_metadata=True,
            filter=pinecone_filter
        )
    else:
        results = index.query(
            vector=query_vec,
            top_k=top_k,
            include_metadata=True
        )

    return [match["metadata"] for match in results["matches"]]


def format_retrieved(items):
    if not items:
        return "No matching items found."

    lines = []
    for item in items:
        if item.get("record_type", "").lower() == "alcohol":
            lines.append(
                f"• {item.get('item_name', 'N/A')}\n"
                f"  Type        : {item.get('beverage_type', 'N/A')}\n"
                f"  Description : {item.get('description', 'N/A')}\n"
                f"  Rating      : {item.get('rating', 'N/A')}\n"
                f"  Best Pairing: {item.get('best_pairing', 'N/A')}\n"
            )
        else:
            lines.append(
                f"• {item.get('item_name', 'N/A')}\n"
                f"  Cuisine     : {item.get('cuisine', 'N/A')}\n"
                f"  Category    : {item.get('category', 'N/A')}\n"
                f"  Dietary     : {item.get('dietary_tags', 'N/A')}\n"
                f"  Spice Level : {item.get('spice_level', 'N/A')}\n"
                f"  Description : {item.get('description', 'N/A')}\n"
                f"  Rating      : {item.get('rating', 'N/A')}\n"
                f"  Best Pairing: {item.get('best_pairing', 'N/A')}\n"
            )
    return "\n".join(lines)

print("done")

# G

ALCOHOL_DISCLAIMER = (
    "\n\n  ALCOHOL NOTICE: Alcoholic beverages are served exclusively "
    "to guests aged 21 and above. A valid government-issued photo ID "
    "will be required on the premises."
)

SYSTEM_PROMPT = """
You are a warm, friendly menu assistant for Saffron Table Bistro.

Guide the guest step by step, never dump everything at once:

STEP 1 - If the guest hasn't chosen a cuisine or alcohol yet:
  Show the menu summary and ask what they'd like to explore.

STEP 2 - Once they pick a cuisine or alcohol:
  For FOOD, ask: Appetizer / Main / Dessert?
  For ALCOHOL, ask: Cocktail / Wine / Beer / Spirit / Liqueur / Sparkling / Mulled Wine?

STEP 3 - For FOOD only, ask: Vegetarian / Chicken / Seafood / Lamb / Beef / Non-Veg / View All?

STEP 4 - Present the retrieved items clearly with:
  Name, Description, Rating, Best Pairing, Spice Level (food) or Beverage Type (alcohol).

RULES:
- ALWAYS add the alcohol disclaimer whenever alcohol items are shown.
- Keep responses concise and friendly.
- Use light emojis for readability.
- Only show items from the retrieved context — do not make up items.
- If no items match, say so and ask the guest to refine their choice.
"""

state = {
    "record_type":   None,
    "cuisine":       None,
    "category":      None,
    "diet":          None,
    "beverage_type": None,
    "_nonveg":       False
}

conversation_history = []

def update_state(user_message):
    msg = user_message.lower()

    # Record type
    if any(w in msg for w in ["alcohol", "drink", "cocktail", "wine", "beer",
                               "spirit", "whiskey", "rum", "gin", "liqueur",
                               "sparkling", "mulled"]):
        state["record_type"] = "Alcohol"
    elif any(w in msg for w in ["food", "eat", "cuisine", "indian", "italian",
                                 "japanese", "chinese", "continental",
                                 "mediterranean", "asian", "north indian",
                                 "asian fusion", "fusion"]):
        state["record_type"] = "Food"

    # Cuisine
    cuisine_map = {
        "indian fusion":   "Indian Fusion",
        "north indian":    "North Indian",
        "continental":     "Continental",
        "japanese":        "Japanese",
        "chinese":         "Chinese",
        "italian":         "Italian",
        "asian fusion":    "Asian Fusion",
        "mediterranean":   "Mediterranean",
    }
    for key, val in cuisine_map.items():
        if key in msg:
            state["cuisine"]      = val
            state["record_type"]  = "Food"
            break

    # Category
    if "appetizer" in msg or "starter" in msg:
        state["category"] = "Appetizer"
    elif "main" in msg or "mains" in msg:
        state["category"] = "Main"
    elif "dessert" in msg or "sweet" in msg:
        state["category"] = "Dessert"

    # Dietary
    if "nonveg" in msg or "non veg" in msg or "non-veg" in msg:
        state["diet"]    = None
        state["_nonveg"] = True
    elif ("veg" in msg) and ("non" not in msg) and ("nonveg" not in msg):
        state["diet"]    = "Vegetarian"
        state["_nonveg"] = False
    elif "vegetarian" in msg:
        state["diet"]    = "Vegetarian"
        state["_nonveg"] = False
    elif "chicken" in msg:
        state["diet"]    = "Chicken"
        state["_nonveg"] = False
    elif "seafood" in msg or "fish" in msg:
        state["diet"]    = "Seafood"
        state["_nonveg"] = False
    elif "lamb" in msg:
        state["diet"]    = "Lamb"
        state["_nonveg"] = False
    elif "beef" in msg:
        state["diet"]    = "Beef"
        state["_nonveg"] = False
    elif "all" in msg:
        state["diet"]    = None
        state["_nonveg"] = False

    # Beverage
    for btype in ["cocktail", "wine", "beer", "spirit", "liqueur",
                  "sparkling", "mulled wine"]:
        if btype in msg:
            state["beverage_type"] = btype.title()


def build_filter(state):
    f = {}

    if state.get("record_type") == "Food":
        f["record_type"] = "Food"
        if state.get("cuisine"):
            f["cuisine"] = state["cuisine"]
        if state.get("category"):
            f["category"] = state["category"]
        if state.get("_nonveg"):
            f["dietary_tags"] = {"$nin": ["Vegetarian"]}
        elif state.get("diet") and state.get("diet") != "All":
            f["dietary_tags"] = state["diet"]

    elif state.get("record_type") == "Alcohol":
        f["record_type"] = "Alcohol"
        if state.get("beverage_type"):
            f["beverage_type"] = state["beverage_type"]

    return f


def retrieve(query, state, top_k=8):
    query_vec       = embedding_model.encode(query).tolist()
    pinecone_filter = build_filter(state)

    if pinecone_filter:
        results = index.query(
            vector=query_vec,
            top_k=top_k,
            include_metadata=True,
            filter=pinecone_filter
        )
    else:
        results = index.query(
            vector=query_vec,
            top_k=top_k,
            include_metadata=True
        )

    return [match["metadata"] for match in results["matches"]]


def format_retrieved(items):
    if not items:
        return "No matching items found."

    lines = []
    for item in items:
        if item.get("record_type", "").lower() == "alcohol":
            lines.append(
                f"• {item.get('item_name', 'N/A')}\n"
                f"  Type        : {item.get('beverage_type', 'N/A')}\n"
                f"  Description : {item.get('description', 'N/A')}\n"
                f"  Rating      : {item.get('rating', 'N/A')}\n"
                f"  Best Pairing: {item.get('best_pairing', 'N/A')}\n"
            )
        else:
            lines.append(
                f"• {item.get('item_name', 'N/A')}\n"
                f"  Cuisine     : {item.get('cuisine', 'N/A')}\n"
                f"  Category    : {item.get('category', 'N/A')}\n"
                f"  Dietary     : {item.get('dietary_tags', 'N/A')}\n"
                f"  Spice Level : {item.get('spice_level', 'N/A')}\n"
                f"  Description : {item.get('description', 'N/A')}\n"
                f"  Rating      : {item.get('rating', 'N/A')}\n"
                f"  Best Pairing: {item.get('best_pairing', 'N/A')}\n"
            )
    return "\n".join(lines)


def chat(user_message):
    update_state(user_message)

    retrieved = retrieve(user_message, state)
    context   = format_retrieved(retrieved)

    augmented = (
        f"{user_message}\n\n"
        f"--- Retrieved menu items ---\n{context}"
    )

    conversation_history.append({"role": "user", "content": augmented})

    response = groq_client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "system", "content": SYSTEM_PROMPT}] + conversation_history,
        temperature=0.4,
        max_tokens=1000
    )

    reply = response.choices[0].message.content

    alcohol_keywords = ["cocktail", "wine", "beer", "whiskey", "vodka", "rum",
                        "gin", "spirit", "liqueur", "sparkling", "mulled", "alcoholic"]
    if any(kw in reply.lower() for kw in alcohol_keywords) and "21" not in reply:
        reply += ALCOHOL_DISCLAIMER

    conversation_history.append({"role": "assistant", "content": reply})
    return reply

print("done")

# botkisthan

refs = _get_reference_values(menua1)
state = {
    "record_type":   None,
    "cuisine":       None,
    "category":      None,
    "diet":          None,
    "beverage_type": None
}
conversation_history = []

print(get_menu_summary(menua1))
print("\n" + "─" * 60 + "\n")

while True:
    user_input = input("You: ").strip()
    if not user_input:
        continue
    if user_input.lower() in ["quit", "exit", "bye", "done", "thanks", "finish"]:
        print("\n Thank you for visiting Saffron Table Bistro. Enjoy your meal!")
        break

    response = chat(user_input)
    print(f"\nAssistant:\n{response}\n")
    print("─" * 60)