# -*- coding: utf-8 -*-
"""reservation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jgWZnXLbZqGgueqpCSEcXjSDE6SUuJLr
"""

!pip install streamlit -q
!pip install supabase -q
!pip install pyngrok -q

!pip install groq -q
!pip install pinecone -q
!pip install sentence-transformers -q

import os
import json
import re
from datetime import datetime

from supabase import create_client, Client

from groq import Groq

from pinecone import Pinecone, ServerlessSpec
from sentence_transformers import SentenceTransformer

GROQ_API_KEY      = "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"
PINECONE_API_KEY  = "pcsk_7HWBE7_TAZGCnBqboH8YRqBh4FNoS6kpcwnUGiFjSWXRYazmuen44BScTqpfPpWNCa2PSi"
PINECONE_INDEX    = "reservations"
SUPABASE_URL      = "https://qhdvjompicmxelwrwtzy.supabase.co"
SUPABASE_KEY      = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFoZHZqb21waWNteGVsd3J3dHp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM4ODAxMDMsImV4cCI6MjA4OTQ1NjEwM30.WzVpkUOq7hINtFI3KJw3uhLnfdjojTyfDHsV3zbzVHk"

groq_client    = Groq(api_key=GROQ_API_KEY)
pc             = Pinecone(api_key=PINECONE_API_KEY)
embedder       = SentenceTransformer("all-MiniLM-L6-v2")
supabase      = create_client(SUPABASE_URL, SUPABASE_KEY)

print ("done")

def table_exists(table_name):
    # Check if a table already exists.
    try:
        supabase.table(table_name).select("*").limit(1).execute()
        return True
    except Exception:
        return False

# tables check
for table in ["reservations", "callbacks"]:
    if table_exists(table):
        print(f"'{table}' found and ready!")
    else:
        print(f"'{table}' not found — go create it in Supabase SQL Editor.")

print("\n Database check complete!")

test_id = f"TEST{datetime.now().strftime('%H%M%S')}"

supabase.table("reservations").insert({
    "id": test_id,
    "name": "Test",
    "phone": "8765432102",
    "date": "March 25",
    "time": "7:30 PM",
    "guests": "2",
    "special_requests": "None",
    "status": "Confirmed"
}).execute()

result = supabase.table("reservations").select("*").eq("id", test_id).execute()
print(f"Done: {result.data[0]['name']}")

# deleting the test row
supabase.table("reservations").delete().eq("id", test_id).execute()
print("Test row cleaned up.")

# pinecone
existing = [i.name for i in pc.list_indexes()]
if "reservations" not in existing:
    pc.create_index(
        name="reservations",
        dimension=384,
        metric="cosine",
        spec=ServerlessSpec(cloud="aws", region="us-east-1")
    )
    print("Pinecone index created!")
else:
    print("Already exists")

# Connect
index = pc.Index("reservations")
print("Pinecone ready!")

# reservation
def save_reservation(data: dict) -> str:
    res_id = f"RES{datetime.now().strftime('%y%m%d%H%M%S')}"
    supabase.table("reservations").insert({
        "id":               res_id,
        "name":             data.get("name", ""),
        "phone":            data.get("phone", ""),
        "date":             data.get("date", ""),
        "time":             data.get("time", ""),
        "guests":           data.get("guests", ""),
        "special_requests": data.get("special_requests", ""),
        "status":           "Confirmed"
    }).execute()
    vector = embedder.encode(f"{data.get('name')} {data.get('date')} {data.get('time')}").tolist()
    index.upsert(vectors=[{
        "id":       res_id,
        "values":   vector,
        "metadata": {"name": data.get("name"), "date": data.get("date"), "id": res_id}
    }])
    return res_id

def find_reservation(query: str):
    # id
    result = supabase.table("reservations").select("*").eq("id", query.upper()).execute()
    if result.data:
        return result.data[0]
    # phone
    result = supabase.table("reservations").select("*").eq("phone", query).execute()
    if result.data:
        return result.data[0]
    # name
    result = supabase.table("reservations").select("*").ilike("name", f"%{query}%").execute()
    if result.data:
        return result.data[0]
    return None

print("done")

# modify
def modify_reservation(res_id: str, field: str, value: str):
    col_map = {
        "Date":             "date",
        "Time":             "time",
        "Guests":           "guests",
        "Special Requests": "special_requests"
    }
    col = col_map.get(field)
    if col:
        supabase.table("reservations").update({col: value}).eq("id", res_id).execute()

# cancel
def cancel_reservation(res_id: str):
    supabase.table("reservations").update({"status": "Cancelled"}).eq("id", res_id).execute()

# callback req
def save_callback(data: dict) -> str:
    ref = f"CB{datetime.now().strftime('%y%m%d%H%M%S')}"
    supabase.table("callbacks").insert({
        "ref":            ref,
        "name":           data.get("name", ""),
        "phone":          data.get("phone", ""),
        "reason":         data.get("reason", ""),
        "preferred_time": data.get("preferred_time", ""),
        "status":         "Pending"
    }).execute()
    return ref

print("done")

CHAT_PROMPT = """
You are a friendly restaurant reservation assistant, like a real human host picking up the phone.

Personality:
- Warm, casual, and genuinely helpful
- Like a real human host, not robotic, not overly formal
- Use natural language, contractions, the occasional "of course!", "absolutely!", "no worries!"
- Keep responses short and conversational, never dump a wall of text
- If someone says hi, hello, hey, etc, greet them back warmly and let them know what you can help with, but keep it short and natural. Like a real person picking up the phone.
- If someone says thanks, bye, done, be nice, thank them for using the service and tell them goodbye. Like a real person picking up the phone.

You collect info for 4 things:
1. New reservation you need: name, phone, date, time, guests, special requests
2. Modify reservation you need: name or phone or booking ID, then what to change
3. Cancel reservation you need: name or phone or booking ID
4. Callback request you need: name, phone, reason, preferred callback time

When you have ALL info collected, end your message with: RESERVED

Never output JSON. Never mention anything technical.

IMPORTANT RULES FOR JSON OUTPUT:
- When you are ready to save, output ONLY the JSON on its own line, no other text in that message
- Do NOT confirm, summarize or say anything else in the same message as the JSON
- First send your confirmation message to the guest
- Then in your NEXT message, send ONLY the raw JSON, nothing else
- Example of WRONG: "Great! {'action': 'save_reservation'...}"
- Example of RIGHT: just the JSON alone on one line, that's it
"""


EXTRACT_PROMPT = """
You extract reservation data from a conversation and output ONLY raw JSON, nothing else.
No explanation, no markdown, no backticks. Just the JSON object.

Output one of these depending on the intent:
{"action": "save_reservation", "data": {"name":"","phone":"","date":"","time":"","guests":"","special_requests":""}}
{"action": "find_reservation", "data": {"query": ""}}
{"action": "modify_reservation", "data": {"field": "Date|Time|Guests|Special Requests", "value": ""}}
{"action": "cancel_reservation", "data": {}}
{"action": "save_callback", "data": {"name":"","phone":"","reason":"","preferred_time":""}}
"""

def ask_groq(messages, system=CHAT_PROMPT):
    response = groq_client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "system", "content": system}] + messages,
        temperature=0.7,
        max_tokens=300
    )
    return response.choices[0].message.content

print("done")

def handle_reservation_action(action: dict, session: dict) -> str:
    name = action.get("action")
    data = action.get("data", {})

    if name == "save_reservation":
        res_id = save_reservation(data)
        session["last_res_id"] = res_id
        return f"[SYSTEM] Reservation saved! ID: {res_id}"

    elif name == "find_reservation":
        record = find_reservation(data.get("query", ""))
        if record:
            session["found_record"] = record
            return (f"[SYSTEM] Found — ID: {record['id']}, "
                    f"Name: {record['name']}, Date: {record['date']}, "
                    f"Time: {record['time']}, Status: {record['status']}")
        return "[SYSTEM] No reservation found."

    elif name == "modify_reservation":
        record = session.get("found_record")
        if record:
            modify_reservation(record["id"], data.get("field"), data.get("value"))
            return f"[SYSTEM] Updated {data.get('field')} to {data.get('value')}"
        return "[SYSTEM] No reservation selected."

    elif name == "cancel_reservation":
        record = session.get("found_record")
        if record:
            cancel_reservation(record["id"])
            return f"[SYSTEM] Reservation {record['id']} cancelled."
        return "[SYSTEM] No reservation selected."

    return None

print("done")

def handle_callback_action(action: dict, session: dict) -> str:
    name = action.get("action")
    data = action.get("data", {})

    if name == "save_callback":
        ref = save_callback(data)
        session["last_cb_ref"] = ref
        return f"[SYSTEM] Callback saved! Ref: {ref}"

    return None

print("done")

def strip_json(text: str) -> str:
    clean = re.sub(r'\{[^{}]*"action"[^{}]*\}', '', text, flags=re.DOTALL)
    return clean.strip()

def extract_action(messages):
    summary = "\n".join([f"{m['role']}: {m['content']}" for m in messages[-6:]])
    raw = ask_groq(
        [{"role": "user", "content": f"Extract the action from this conversation:\n{summary}"}],
        system=EXTRACT_PROMPT
    )
    try:
        clean = raw.strip().strip("```json").strip("```").strip()
        return json.loads(clean)
    except:
        return None

def chat(user_msg: str, messages: list, session: dict) -> str:
    messages.append({"role": "user", "content": user_msg})
    reply = ask_groq(messages)

    triggers = ["RESERVED", "all set", "you're booked", "reservation is confirmed", "callback"]
    triggered = any(t.lower() in reply.lower() for t in triggers)

    if triggered:
        clean_reply = strip_json(reply)
        action = extract_action(messages)
        if action:
            result = handle_reservation_action(action, session) or \
                     handle_callback_action(action, session)
            if result:
                messages.append({"role": "assistant", "content": clean_reply})
                messages.append({"role": "user", "content": result})
                final_reply = strip_json(ask_groq(messages))
                messages.append({"role": "assistant", "content": final_reply})
                return final_reply
        messages.append({"role": "assistant", "content": clean_reply})
        return clean_reply

    messages.append({"role": "assistant", "content": strip_json(reply)})
    return strip_json(reply)

print("done")

messages = []
session  = {}

print("Restaurant Reservation Assistant")

while True:
    user_input = input("You: ")
    if user_input.lower() in ["quit", "stop", "done", "exit", "bye", "goodbye"]:
        print("Bot: Thanks for reaching out, hope to see you soon!")
        break

    reply = chat(user_input, messages, session)
    print(f"\nBot: {reply}\n")

"""# test

result = save_reservation({
    "name": "jhuhyugyu",
    "phone": "778776778",
    "date": "10th April",
    "time": "7pm",
    "guests": "9",
    "special_requests": "burr"
})
print(f"ID: {result}")
"""